# Generated by Django 5.0.6 on 2024-05-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_facility_patient_confirm_password_patient_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
