# Generated by Django 5.0.6 on 2024-05-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_facility_appointment_management_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='firstname_doctor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='lastname_doctor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
