# Generated by Django 5.0.6 on 2024-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='name',
            new_name='healthcare_name',
        ),
        migrations.AddField(
            model_name='facility',
            name='departments',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='resources',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
