# Generated by Django 5.0.6 on 2024-05-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_name_facility_healthcare_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='resources',
            field=models.TextField(max_length=200),
        ),
    ]
