# Generated by Django 5.0.6 on 2024-05-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_appointment_schedule_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
