# Generated by Django 5.0.6 on 2024-05-24 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_patient_confirm_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment_management',
            new_name='AppointmentManagement',
        ),
        migrations.RenameModel(
            old_name='Patient_Appointment',
            new_name='PatientAppointment',
        ),
        migrations.RenameModel(
            old_name='UserProfileManagement',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='appointmentmanagement',
            old_name='doctor_management',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointmentmanagement',
            old_name='patient_management',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='firstname_doctor',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='lastname_doctor',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='healthcare_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='facility',
            name='resources',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.doctor'),
        ),
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('details', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment_Schedule',
        ),
    ]
